spring:

  datasource:
    url: jdbc:mysql://localhost:3306/monopoly-db
    username: root
    password: pass
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    showSql: true
    generateDdl: true
    hibernate:
      ddlAuto: update
      naming:
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.format_sql: true

logging:

  level:
    org.hibernate.SQL: DEBUG